spring:
  application:
    name: nettyapp
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3307}/${MYSQL_DATABASE:db_callback}?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_USERNAME:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: caffeine
netty:
  port: ${NETTY_PORT:8980}
  ssl: ${NETTY_SSL:false}
  threads: ${NETTY_THREADS:1}
  sslkey: classpath:key.pem
  sslcert: classpath:server.pem
mybatis:
  config-location: classpath:mybatis.xml
